---
- hosts: all
  become: yes

  vars:
    mysql_root_password: "Password1"

  tasks:
  - name: Set a hostname
    hostname:
      name: hades

  - name: Install whois for passwd stuff
    apt:
      name: whois
      state: present
   
  - name: PASSWORDS | Update loud passwd
    user:
      name: loud
      password: "{{ hellograder | mkpasswd -m sha-512 }}"
      update_password: always

  - name: create cybe466grader
    user:
      name: cybe466grader
      createhome: True
      uid: 1041
      group: admin,sudo

  - name: PASSWORDS | Update grader password
    user:
      name: cybe466grader
      password: "{{ hellograder | mkpasswd -m sha-512 }}"
      update_password: always

  - name: create dbremoteuser
    user:
      name: dbremoteuser
      comment: 
      uid: 1040
      group: admin