---
- hosts: all
  become: yes

  vars:
    mysql_root_password: "Password1"

  tasks:
  - name: Set a hostname
    hostname:
      name: hades
   
  - name: PASSWORDS | Update loud passwd
    user:
      name: loud
      password: $6$C4zm.pBZt$ProPf1z41.JVLpY2tLTkvsWoCp2pEAc2LUwgvoQSUesylbr13LYTsB3ERDlzGMnLoIQbNQG3ABDXJ.uD.6NEe1
      update_password: always

  - name: create cybe466grader
    user:
      name: cybe466grader
      createhome: True
      uid: 1041
      group: sudo

  - name: PASSWORDS | Update grader password
    user:
      name: cybe466grader
      password: $6$C4zm.pBZt$ProPf1z41.JVLpY2tLTkvsWoCp2pEAc2LUwgvoQSUesylbr13LYTsB3ERDlzGMnLoIQbNQG3ABDXJ.uD.6NEe1
      update_password: always

  - name: create dbremoteuser
    user:
      name: dbremoteuser
      comment: 
      uid: 1040
      group: sudo